export default {
  products: [
    {
      _id: "1",
      name: "Slim SHirt",
      category: "Shirts",
      image: "/images/p1.png",
      brand: "Nike",
      price: 60,
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "2",
      name: "Slim SHirt",
      category: "Shirts",
      image: "/images/p1.png",
      brand: "Nike",
      price: 60,
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "3",
      name: " Pants Fit ",
      category: "Pants",
      image: "/images/p1.png",
      brand: "Nike",
      price: 60,
      rating: 4.2,
      numReviews: 10,
    },
    {
      _id: "4",
      name: "Jeans",
      category: "Pants",
      image: "/images/p1.png",
      brand: "Nike",
      price: 60,
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "4",
      name: "Slim SHirt",
      category: "Shirts",
      image: "/images/p1.png",
      brand: "Nike",
      price: 60,
      rating: 4.5,
      numReviews: 10,
    },
    {
      name: "Fit ",
      category: "Pants",
      image: "/images/p1.png",
      brand: "Nike",
      price: 60,
      rating: 4.2,
      numReviews: 10,
    },
  ],
};
